version: '3.8'

services:

  foodgram_db:
    image: postgres:13.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
       - ../backend/.env

  backend:
    image: crush04anechka/foodgram_back:v1
    container_name: backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - foodgram_db
    env_file:
      - ../backend/.env

  frontend:
    image: crush04anechka/foodgram_front:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  db_volume: