# Generated by Django 4.1.4 on 2022-12-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='http://127.0.0.1:8000/recipes/images/header_.jpg', upload_to='recipes/images/', verbose_name='Картинка, закодированная в Base64'),
            preserve_default=False,
        ),
    ]
