# Generated by Django 4.1.4 on 2022-12-31 13:07

import django.core.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amount',
            options={'default_related_name': 'amount', 'verbose_name': 'Кол-во ингредиента в рецепте', 'verbose_name_plural': 'Кол-во ингредиентов в рецептах'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.validate_color], verbose_name='Цвет в HEX'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[recipes.validators.validate_name], verbose_name='Название'),
        ),
    ]
